# Generated by Django 3.0.4 on 2020-03-31 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.IntegerField()),
                ('occu', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=200)),
                ('user_first', models.CharField(max_length=200)),
                ('user_last', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_name', models.CharField(max_length=200)),
                ('hos_pass', models.CharField(max_length=200)),
                ('hos_email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('date_start', models.DateField()),
                ('time_start', models.TimeField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bed')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doc')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hos'),
        ),
    ]
