# Generated by Django 3.0.4 on 2020-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bed_type',
            field=models.IntegerField(null=True),
        ),
    ]
