# Generated by Django 3.0.4 on 2020-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_bed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='patient_mob',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
