# Generated by Django 3.0.4 on 2020-03-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200331_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bed_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient_mob',
            field=models.CharField(default='78946', max_length=10),
        ),
    ]
